import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "Qui/components/layout/Layout";
import Toast from "Qui/utils/toast";
import Provider from "Qui/utils/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Toast/>
          <Layout>
          {children}
          </Layout>
        </Provider>
        </body>
    </html>
  );
}
